/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * Generates, from the release pages and data (see lib/releases.ts):
 *
 * - blog/releases/*.md: one news post per release, so releases are listed on
 *   /news, in the RSS/Atom feeds and on the tag pages next to regular posts.
 * - src/data/generated/releases.json: the same list, for the home page and the
 *   download pages.
 *
 * Both are build outputs, ignored by git and regenerated by `pnpm start`,
 * `pnpm build` and `pnpm typecheck`. Edit the release pages, never these files.
 */

import fs from 'node:fs';
import path from 'node:path';
import {collectReleases, plainText, siteDir, type Release} from './lib/releases.ts';

const newsDir = path.join(siteDir, 'blog/releases');
const dataFile = path.join(siteDir, 'src/data/generated/releases.json');

/**
 * The blog orders posts by date only, so releases published the same day are
 * given one second apart, newest version last, to keep their order stable.
 */
function timestamps(releases: Release[]): Map<Release, string> {
  const result = new Map<Release, string>();
  const byDate = new Map<string, Release[]>();
  for (const release of releases) {
    byDate.set(release.releaseDate, [...(byDate.get(release.releaseDate) ?? []), release]);
  }
  for (const [date, sameDay] of byDate) {
    // `releases` is sorted newest version first within a day.
    sameDay.forEach((release, index) => {
      const seconds = String(sameDay.length - 1 - index).padStart(2, '0');
      // The blog plugin reads dates without a time zone as UTC.
      result.set(release, `${date}T00:00:${seconds}`);
    });
  }
  return result;
}

function newsPost(release: Release, date: string): string {
  const summary = release.summary ?? `${release.title}.`;
  const links = [`See the [release page](${release.url}) for the downloads`];
  if (release.releaseNotes) {
    links.push(`the [release notes](${release.releaseNotes}) for the full list of changes`);
  }
  // JSON strings are valid YAML scalars and need no further escaping.
  const frontMatter = {
    slug: release.newsSlug,
    title: release.title,
    date,
    authors: ['activemq-pmc'],
    tags: ['release', release.component],
    description: plainText(summary),
    release_page: release.url,
  };
  const yaml = Object.entries(frontMatter)
    .map(([key, value]) => `${key}: ${JSON.stringify(value)}`)
    .join('\n');
  return `---\n${yaml}\n---\n\n${summary}\n\n<!-- truncate -->\n\n${links.join(' and ')}.\n`;
}

const releases = collectReleases();
const dates = timestamps(releases);

fs.rmSync(newsDir, {recursive: true, force: true});
fs.mkdirSync(newsDir, {recursive: true});
for (const release of releases) {
  const file = `${release.releaseDate}-${path.basename(release.newsSlug)}.md`;
  fs.writeFileSync(path.join(newsDir, file), newsPost(release, dates.get(release)!));
}

fs.mkdirSync(path.dirname(dataFile), {recursive: true});
const data = releases.map((release) => ({
  ...release,
  summary: release.summary && plainText(release.summary),
}));
fs.writeFileSync(dataFile, `${JSON.stringify(data, null, 2)}\n`);

console.log(`Generated news posts for ${releases.length} releases in ${path.relative(siteDir, newsDir)}`);
